### ISSUE TITLE
Formatting newlines (eg in large SQL queries)

### ISSUE THREAD

**Issue by tombh** [thessem/zap-prettyconsole#2]
First off, thank you! I was so happy to see this and that it was so easy. Also, I see that part of your motivation is being a fan of error wrapping and stacktraces, which is part of why I'm currently switching out the logging code in my project.

So I wonder if there's a way to make the newlines in my [pgx](https://github.com/jackc/pgx) display? This is an example fragment:
`3:02PM INF > Exec commandTag=DO pid=2930363 sql=DO $$\n BEGIN\n CREATE TABLE IF NOT EXISTS http_sessions (\n ...`

Is it something that this package can do? Or is it something I need to change in pgx or zap itself? Thanks for any tips ✨

**Comment by thessem** [comment]
This is an interesting feature request. Thank you. I am a little limited by needing to work through the zap type interfaces (e.g., their zap.String() method doesn't accept arguments) but I may be able to get something working through `zap.Interface(prettyconsole.StringBlock(yourString))` or similar.

Heads up, I've just started a new job and I don't have a huge amount of spare time at the moment, but soon I will be using this library for work again, and I'll definitely have the mental capacity to hone this on my weekends.

**Comment by thessem** [comment]
Perhaps the prettylogger could take configuration of a list of "safe" keys and run `addIndentedString` on those keys instead, which would make the strings output similarly to the error outputs.

**Comment by thessem** [comment]
Added in [0922045](https://github.com/thessem/zap-prettyconsole/commit/09220456fee8abe59f9d2661f8377cc9de7bdfaa), and released in v0.4.0. Check out Readme for usage and a visual of how it looks.

**Comment by danielriddellsh** [comment]
this is great for other fields, but how can I get it to apply to the message field. This is the only field where \n etc don't get formatted correctly

**Comment by tombh** [comment]
BTW, @thessem thanks for doing that, it looks great! I'm not working in that codebase anymore so haven't been able to check it out myself yet, but hopefully will have another chance soon.
